language: python

python:
    - "2.7"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"


install:
    - pip install -r dev-requirements.txt
    - pip install -e .

script:
    - make test

notifications:
    email: false
